INSERT INTO categories (name)
VALUES
    ('Food'),
    ('Tristan - WTF'),
    ('Mar - WTF'),
    ('Household Discretionary'),
    ('Date'),
    ('Eating Out'),
    ('Clothes'),    
    ('Tech Budget'),
    ('Decorations'),
    ('Gifts'),
    ('Furniture'),
    ('Gas'),
    ('Laundry'),
    ('Haircuts'),
    ('Medical'),
    ('Classroom'),
    ('Birthday Budget'),
    ('Down payment'),
    ('Vacation'),
    ('Rent'),
    ('Car Maintenance'),
    ('Health Insurance'),
    ('Car Payment'),
    ('Phone Bill'),
    ('Car insurance'),
    ('Gas Power'),
    ('Electricity'),
    ('Retirement Contribution'),
    ('Savings Contribution'),
    ('Christmas Budget'),
    ('Christmas Siblings');
